docs/artefacts/operators.md, docs/overview.md, docs/tremor-script/index.md
Mainly docs for the implementation in https://github.com/wayfair-tremor/tremor-runtime/pull/59
=> Docs for pipeline state mechanism

docs/ConstraintsLimitations.md, docs/artefacts/offramps.md, docs/artefacts/onramps.md, docs/artefacts/operators.md, docs/development/benchmarks/LogstashBenchmark.md, docs/development/issue-investigation.md, docs/operations/configuration.md, docs/overview.md
* Document QoS operators
* Ducument async use
* Document GD
* Update onramps/offramps to state their GD/CB behavior.
=> Update docs for sink/source/async work

.vscode/settings.json, docs/Contributing.md, docs/development/debugging.md, docs/development/profiling.md, docs/development/quick-start.md, docs/development/testing.md, docs/workshop/examples/00_passthrough/etc/tremor/config/00_ramps.yaml, docs/workshop/examples/01_filter/etc/tremor/config/00_ramps.yaml, docs/workshop/examples/02_transform/etc/tremor/config/00_ramps.yaml, docs/workshop/examples/03_validate/etc/tremor/config/00_ramps.yaml, docs/workshop/examples/10_logstash/etc/tremor/config/00_ramps.yaml, docs/workshop/examples/11_influx/etc/tremor/config/00_ramps.yaml
update mentions of tremor-sever to give the right command with tremor unified cli
=> remove tremor-server references

.github/workflows/alex.yaml
=> Update alex to 1.1.2 and only include .md files.

docs/tremor-script/index.md
Add tuple pattern explanation and a user intention focused description to
each of the patterns: array, tuple, and record
=> Update pattern docs

docs/tremor-query/index.md, docs/tremor-script/index.md
Add example for trickle windows that are script based and pull data from the event
=> Add example for a scripted window

course/operations/index.md, course/overview/index.md
=> Small adaptions for second workshop.

docs/tremor-query/index.md
=> correct eviction_period description

docs/workshop/examples/36_quota_service/etc/tremor/config/internal_error_processing.trickle, docs/workshop/examples/36_quota_service/etc/tremor/config/logs.trickle, docs/workshop/examples/36_quota_service/etc/tremor/config/logs.yaml
Also add template for metrics collection there
=> Fix startup for quota service example

docs/artefacts/offramps.md, docs/workshop/examples/11_influx/etc/tremor/config/00_ramps.yaml, docs/workshop/examples/32_proxies_lt_http/README.md, docs/workshop/examples/32_proxies_lt_http/etc/tremor/config/config.yaml, docs/workshop/examples/35_reverse_proxy_load_balancing/README.md, docs/workshop/examples/35_reverse_proxy_load_balancing/etc/tremor/config/config.yaml, docs/workshop/examples/37_configurator/etc/tremor/config/main.yaml
We changed the rest offramp config to take a struct instead of a string, this reflects the change.
=> Update all the examples to reflect changs in the rest offramp config

Makefile, docs/artefacts/offramps.md
Adds docs for the KV connector
=> Add docs for KV

docs/artefacts/offramps.md
=> highlight commented json as js

docs/operations/linked-transports.md
Make the list of ramps that support LT exhaustive
=> Add ramps that support LT to the list of supported ramps

docs/tremor-script/index.md
Small update on match documentation to mirror current reality
=> Update match docs

docs/index.md
~Nots~ 
Notes
Signed-off-by: yatinmaan <yatinmaan1@gmail.com>
=> Draft: Fix Typo

docs/artefacts/offramps.md
=> Add docs for es actions

docs/artefacts/onramps.md
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
Add docs for stdin onramp.
=> Add docs for stdin onramp

docs/artefacts/offramps.md, docs/artefacts/onramps.md
Signed-off-by: Darach Ennis <darach@gmail.com>
=> Add CNCF OpenTelemetry connector docs

docs/operations/linked-transports.md
=> Document correlation with linked transports.

docs/workshop/examples/40_otel_passthrough/README.md, docs/workshop/examples/40_otel_passthrough/docker-compose.yaml, docs/workshop/examples/40_otel_passthrough/etc/otel/collector-config.yaml, docs/workshop/examples/40_otel_passthrough/etc/tremor/config/00_ramps.yaml, docs/workshop/examples/40_otel_passthrough/etc/tremor/config/01_binding.yaml, docs/workshop/examples/40_otel_passthrough/etc/tremor/config/02_mapping.yaml, docs/workshop/examples/40_otel_passthrough/etc/tremor/config/example.trickle, docs/workshop/examples/40_otel_passthrough/etc/tremor/logger.yaml
Signed-off-by: Darach Ennis <darach@gmail.com>
=> Add simple CNCF OpenTelemetry passthrough workshop

docs/artefacts/offramps.md, docs/artefacts/onramps.md
Add topic, offset, partition and timestamp to kafka metadata
=> Add topic, offset, partition and timestamp to kafka metadata

docs/artefacts/offramps.md
Fixes a formatting issue discovered by Jemshad.
Signed-off-by: Darach Ennis <darach@gmail.com>
=> Fix elastic offramp formatting

docs/artefacts/codecs.md, docs/artefacts/offramps.md, docs/artefacts/onramps.md
Signed-off-by: Darach Ennis <darach@gmail.com>
=> Sundry typo, grammar and spelling fixes for artefacts

docs/operations/configuration-walkthrough.md, docs/operations/configuration.md
While we are intending to kill it and replace it with Troy, this still needs to be unconfused.
=> Try to address some configuration confusions around mappings

docs/workshop/examples/10_logstash/README.md
Couple of text fixes in the config example comments
=> Comment text fixes

docs/artefacts/offramps.md
=> Added docs for Google Cloud Storage connector

docs/artefacts/offramps.md, docs/tremor-script/index.md
* Add special paths to tremor-script overview
* Add note about elastic error response formats and different kinds thereof
=> Some minor improvements

docs/artefacts/offramps.md
* Add `key` to responses
* Add `$kv.op` metadata
=> Add docs for changes in KV offramp

docs/artefacts/offramps.md, docs/artefacts/onramps.md
Signed-off-by: Manuel Stein <manuel.stein@nokia-bell-labs.com>
=> added amqp onramp/offramp doc

docs/artefacts/offramps.md, docs/artefacts/onramps.md
=> docs for pubsub

Makefile
=> Prepare docs release 0.11.4

docs/artefacts/onramps.md
Hi,
I noticed the issue that metronome has no example, so I added one, I hope that helps!
=> Add example for metronome

docs/artefacts/onramps.md
=> add example for crononome

docs/artefacts/onramps.md
Hiya!
Just a few minor typo and grammar fixes. I hope you find them helpful.
Cheers!
=> Sundry typo, grammar and spelling fixes for onramps

docs/operations/configuration.md, docs/tremor-query/modules.md, docs/tremor-script/extractors/datetime.md, docs/tremor-script/modules.md, docs/workshop/examples/12_postgres_timescaledb/README.md, docs/workshop/examples/38_polling_alerts/README.md, docs/workshop/examples/40_otel_passthrough/README.md, docs/workshop/examples/44_otel_elastic_apm/README.md
=> Clarify default TREMOR_PATH values

.gitignore, docs/artefacts/onramps.md, docs/workshop/examples/14_syslog_udp/README.md, docs/workshop/examples/14_syslog_udp/docker-compose.yaml, docs/workshop/examples/14_syslog_udp/etc/tremor/config/00_ramps.yaml, docs/workshop/examples/14_syslog_udp/etc/tremor/config/01_binding.yaml, docs/workshop/examples/14_syslog_udp/etc/tremor/config/02_mapping.yaml, docs/workshop/examples/14_syslog_udp/etc/tremor/config/consumer.trickle, docs/workshop/examples/14_syslog_udp/etc/tremor/config/producer.trickle, docs/workshop/examples/14_syslog_udp/etc/tremor/logger.yaml, docs/workshop/examples/14_syslog_udp/input.json, docs/workshop/examples/14_syslog_udp/inputs.txt, docs/workshop/examples/15_syslog_udp_dns/README.md, docs/workshop/examples/15_syslog_udp_dns/docker-compose.yaml, docs/workshop/examples/15_syslog_udp_dns/etc/tremor/config/00_ramps.yaml, docs/workshop/examples/15_syslog_udp_dns/etc/tremor/config/01_binding.yaml, docs/workshop/examples/15_syslog_udp_dns/etc/tremor/config/02_mapping.yaml, docs/workshop/examples/15_syslog_udp_dns/etc/tremor/config/consumer.trickle, docs/workshop/examples/15_syslog_udp_dns/etc/tremor/config/dns.trickle, docs/workshop/examples/15_syslog_udp_dns/etc/tremor/config/producer.trickle, docs/workshop/examples/15_syslog_udp_dns/etc/tremor/logger.yaml, docs/workshop/examples/15_syslog_udp_dns/input.json, docs/workshop/examples/15_syslog_udp_dns/inputs.txt, docs/workshop/examples/32_proxies_lt_http/README.md
Add workshops for syslog and examples for the DNS sink
=> Baseline for syslog_udp and syslog_udp_dns workshops

docs/artefacts/offramps.md, docs/artefacts/onramps.md
=> Updated docs for pub/sub

docs/artefacts/onramps.md
Docs in reference to tremor-rs/tremor-runtime#1065
Signed-off-by: Daksh Chauhan <dak-x@outlook.com>
=> Add docs for SSE onramp.

docs/internal/LocalMkdocsSetup.md, docs/internal/RunDocumentationManjaro.md, docs/internal/transform.md, mkdocs.yml.in
Hello.
I added a guide for setting up and running MkDocs on Manjaro Linux distribution. I hope it will helpful for anyone using Manjaro.
Cheers!
=>  New section on how to run documentation on Manjaro Linux

docs/artefacts/onramps.md, mkdocs.yml.in
Add links that were left out in the syslog PR (and fix two other missing links while at it)
=> Fix merge links

docs/artefacts/postprocessors.md, docs/artefacts/preprocessors.md
Signed-off-by: Daksh Chauhan <dak-x@outlook.com>
Related Issue: tremor-rs/tremor-runtime#1100
Related PR: tremor-rs/tremor-runtime#1101
=> Update addition of zstd pre-and-postprocessor.

docs/artefacts/onramps.md
=> Add env source

docs/tremor-query/index.md
Remove warnings that are no longer needed
=> Update windowing docs

docs/workshop/examples/00_passthrough/etc/tremor/config/01_binding.yaml, docs/workshop/examples/01_filter/etc/tremor/config/01_binding.yaml, docs/workshop/examples/02_transform/etc/tremor/config/01_binding.yaml, docs/workshop/examples/03_validate/etc/tremor/config/01_binding.yaml, docs/workshop/examples/10_logstash/etc/tremor/config/01_binding.yaml, docs/workshop/examples/11_influx/etc/tremor/config/01_binding.yaml, docs/workshop/examples/14_syslog_udp/etc/tremor/config/01_binding.yaml, docs/workshop/examples/15_syslog_udp_dns/etc/tremor/config/01_binding.yaml, docs/workshop/examples/23_kafka_gd/etc/tremor_in/config/01_binding.yaml, docs/workshop/examples/23_kafka_gd/etc/tremor_out/config/01_binding.yaml, docs/workshop/examples/38_polling_alerts/etc/tremor/config/01_binding.yaml, docs/workshop/examples/39_kafka_elastic_correlation/etc/tremor_in/config/01_binding.yaml
quick typo fix in a few places.
=> inpunt -> input
