tremor-rs/tremor-www-docs

docs/index.md
* change 2 spaces to 4 for nested lists
* fix typo in `folder` spelling
r? @darach
=> fix indentation and typo in folder

docs/Glossary.md, docs/development/quick-start.md, docs/index.md, docs/operations/configuration.md, docs/tremor-script/extractors/glob.md, docs/tremor-script/recipes.md, docs/workshop/README.md
* Add recipe for checking variable presence in tremor-script
* Document trickle filename to pipeline id behavior
* Add meta variables to the glossary
* Improve dev docs and workshop discovery 
* Cleanup some typos and links
=> Add new tremor-script recipe, plus some cleanup

docs/artefacts/offramps.md, docs/workshop/examples/00_passthrough/etc/tremor/logger.yaml, docs/workshop/examples/01_filter/etc/tremor/logger.yaml, docs/workshop/examples/02_transform/etc/tremor/logger.yaml, docs/workshop/examples/03_validate/etc/tremor/logger.yaml, docs/workshop/examples/10_logstash/etc/tremor/logger.yaml, docs/workshop/examples/11_influx/etc/tremor/logger.yaml, docs/workshop/examples/12_postgres_timescaledb/etc/tremor/logger.yaml, docs/workshop/examples/20_transient_gd/etc/tremor/logger.yaml, docs/workshop/examples/21_persistent_gd/etc/tremor/logger.yaml, docs/workshop/examples/22_roundrobin/etc/tremor/logger.yaml, docs/workshop/examples/30_servers_lt_http/etc/tremor/logger.yaml, docs/workshop/examples/31_servers_lt_ws/README.md, docs/workshop/examples/31_servers_lt_ws/etc/tremor/config/config.yaml, docs/workshop/examples/31_servers_lt_ws/etc/tremor/logger.yaml, docs/workshop/examples/32_proxies_lt_http/README.md, docs/workshop/examples/32_proxies_lt_http/etc/tremor/config/config.yaml, docs/workshop/examples/32_proxies_lt_http/etc/tremor/config/internal_error_processing.trickle, docs/workshop/examples/32_proxies_lt_http/etc/tremor/logger.yaml, docs/workshop/examples/33_proxies_lt_ws/README.md, docs/workshop/examples/33_proxies_lt_ws/etc/tremor/config/config.yaml, docs/workshop/examples/33_proxies_lt_ws/etc/tremor/config/pass_errors.trickle, docs/workshop/examples/33_proxies_lt_ws/etc/tremor/logger.yaml, docs/workshop/examples/34_bridges_lt_http_ws/README.md, docs/workshop/examples/34_bridges_lt_http_ws/etc/tremor/config/config.yaml, docs/workshop/examples/34_bridges_lt_http_ws/etc/tremor/config/internal_error_processing.trickle, docs/workshop/examples/34_bridges_lt_http_ws/etc/tremor/logger.yaml, docs/workshop/examples/35_reverse_proxy_load_balancing/etc/tremor/logger.yaml
Include proper error handling for LT websocket workshops.
Also document newrelic offramp, initially added via https://github.com/tremor-rs/tremor-runtime/pull/357
=> Improve LT websocket workshops and document newrelic offramp

docs/workshop/examples/00_passthrough/etc/tremor/logger.yaml, docs/workshop/examples/01_filter/etc/tremor/logger.yaml, docs/workshop/examples/02_transform/etc/tremor/logger.yaml, docs/workshop/examples/03_validate/etc/tremor/logger.yaml, docs/workshop/examples/10_logstash/etc/tremor/logger.yaml, docs/workshop/examples/11_influx/etc/tremor/logger.yaml, docs/workshop/examples/12_postgres_timescaledb/etc/tremor/logger.yaml, docs/workshop/examples/20_transient_gd/etc/tremor/logger.yaml, docs/workshop/examples/21_persistent_gd/etc/tremor/logger.yaml, docs/workshop/examples/22_roundrobin/etc/tremor/logger.yaml, docs/workshop/examples/23_kafka_gd/docker-compose.yaml, docs/workshop/examples/23_kafka_gd/etc/tremor_in/logger.yaml, docs/workshop/examples/23_kafka_gd/etc/tremor_out/logger.yaml, docs/workshop/examples/30_servers_lt_http/etc/tremor/logger.yaml, docs/workshop/examples/31_servers_lt_ws/etc/tremor/logger.yaml, docs/workshop/examples/32_proxies_lt_http/etc/tremor/logger.yaml, docs/workshop/examples/33_proxies_lt_ws/etc/tremor/logger.yaml, docs/workshop/examples/34_bridges_lt_http_ws/etc/tremor/logger.yaml, docs/workshop/examples/35_reverse_proxy_load_balancing/etc/tremor/logger.yaml, docs/workshop/examples/36_quota_service/etc/tremor/logger.yaml, docs/workshop/examples/37_configurator/etc/tremor/logger.yaml
Otherwise insightful log messages from tremor might get lost, leaving users clueless.
@anupdhml this might put some more log messages into the users face. i think we can tweak on a case per case basis if needed. What do you think?
=> Only log to stdout for all workshop examples.

docs/artefacts/postprocessors.md, docs/artefacts/preprocessors.md
Along with some cleanup for other preprocessors/postprocessors
Also documents the lines preprocessors that were added in https://github.com/tremor-rs/tremor-runtime/pull/285.
=> Doc cleanup for lines preprocessor

docs/artefacts/onramps.md
Without this, when tremor is shutdown immediately, tremor might not be able to handle all events, leading to confusion.
We might need to rethink the options or defaults for this onramp, but at least we need to document all the options first.
=> Document `sleep_on_done` option for file source.

docs/workshop/examples/00_passthrough/README.md
Fix binding id in `passthrough` example to reflect that of actual file.
=> fix id of binding

docs/tremor-query/walkthrough.md, docs/workshop/examples/01_filter/README.md, docs/workshop/examples/02_transform/README.md, docs/workshop/examples/03_validate/README.md
* fix query in filter workshop
* few typos
* fix query in tremor-query walkthrough
=> Typo fixes in workshop examples

docs/tremor-query/index.md
* eviction_period example was described wrong.
* clarified that empty windows (without events flowing through them) are possible for time based windows
=> Clarify time based window behaviour.

docs/artefacts/offramps.md, docs/artefacts/onramps.md
We might want to consider adding a numeric config called `max_retries` which limits how often a failed message is retried until it is skipped. Otherwise we might run into infinite loops when `enable.auto.commit: false` is set and events result in failures persistently. Any thoughts on this?
=> Update kafka docs for new config values and autocommit behaviour

docs/tremor-query/index.md, docs/tremor-query/walkthrough.md, docs/workshop/examples/11_influx/etc/tremor/config/00_ramps.yaml, docs/workshop/examples/11_influx/etc/tremor/config/01_binding.yaml, docs/workshop/examples/11_influx/etc/tremor/config/example.trickle
Adapt docs to new restrictions for the select target expression introduced in: https://github.com/tremor-rs/tremor-runtime/pull/828
=> Adapt to new select target restrictions

docs/artefacts/offramps.md
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
Include request headers, method and endpoint as a metadata variable for response events.
=> Add docs for request metadata in response

docs/artefacts/offramps.md, docs/artefacts/onramps.md
Documentation related to https://github.com/tremor-rs/tremor-runtime/pull/766, integrating Kafka message headers available as the `$kafka_headers` metadata variable.
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
=> Add docs for Kafka message headers

docs/CII.md, docs/api.md, docs/artefacts/codecs.md, docs/artefacts/offramps.md, docs/artefacts/onramps.md, docs/artefacts/postprocessors.md, docs/artefacts/preprocessors.md, docs/development/issue-investigation.md, docs/development/quick-start.md, docs/operations/linked-transports.md, docs/overview.md, docs/policies/security.md, docs/tremor-query/index.md, docs/tremor-query/pp.md, docs/tremor-query/walkthrough.md, docs/tremor-script/functions.md, docs/tremor-script/index.md, docs/tremor-script/pp.md
Hi there!
I'm trying to know more about Tremor for the GSoC projects and found a few typos in the docs. So I went ahead and did a manual review of the entire docs while I was at it. Let me know if any of these changes is wrong.
Also, not sure why the CI is failing.
=> Fix a lot of typos

docs/artefacts/offramps.md, docs/artefacts/onramps.md
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
Docs for the NATS offramp and onramp. [Related PR](https://github.com/tremor-rs/tremor-runtime/pull/866)
=> Add docs for nats onramp and offramp

mkdocs.yml.in
=> Fix small yaml typo in mkdocs.yml template.

docs/development/benchmarking.md
Copying and pasting the commands in the document does not make the program work.
This ticket corrects a typo in `real-workflow-througput-json`.
```bash
$ ./bench/run real-workflow-througput-json
++ dirname ./bench/run
+ BENCH_ROOT=./bench
+ . ./bench/common.inc
++ group=tremor-runtime
+++ basename ./bench/run
++ benchmark=run
++ benchmark=run
+++ git rev-parse HEAD
++ hash=bfa5bc0729ad00758a036692bf64cbc35cbe2965
+++ date +%s
++ date=1619926217
+ 'BENCH_EXTRA?='
./bench/run: line 11: BENCH_EXTRA?=: command not found
+ file=real-workflow-througput-json
+ '[' '!' -f real-workflow-througput-json ']'
+ file=./bench/real-workflow-througput-json.yaml
+ '[' '' = devcontainer ']'
+ TARGET_ROOT=target
+ '[' '!' -z ']'
+ '[' '' = debug ']'
+ TARGET_MODE=release
+ '[' '!' -f …
```
=> Fix benchmark example name

docs/workshop/examples/36_quota_service/data/logs_sample, docs/workshop/examples/36_quota_service/logger.sh
Generate dynamic timestamp for each log message, so that the change in volume can be visible after quota change thru api.
=> Add current timestamp to logs generated for Quota testing

docs/artefacts/offramps.md, docs/artefacts/onramps.md
Added lines preprocessor and postprocessor in the config examples of gcs, gpub, gsub. Since for stream-based connectors, we require preprocessor and postprocessor as the source doesn't know where or when a packet ends.
=> fixed config example for gcloud connectors

docs/artefacts/offramps.md, docs/artefacts/onramps.md
I misunderstood gcloud sources and sinks as stream based and had added the `lines` preprocessor and postprocessor in the examples. Fixed it to what it was before. Sorry!! ;-;
=> fixing gcloud connectors example
